---

- hosts: all
  become: true
  tasks:
    - name: copy files
      copy: 
        src: ./script.sh
        dest: /home/vishal/Desktop
    - name: buri buri zai mon
      shell: sh /home/vishal/Desktop/script.sh >> log.txt
